import type { Vehicle } from '../types'

const now = new Date().toISOString()

/** Sample fleet for preview when the database has no vehicles yet. */
export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: 'demo-gold-1',
    name: 'Gold Camry',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2024,
    category: 'sedan',
    package: 'gold',
    dailyRate: 79,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1621007947382-bcb3c783716e?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-2',
    name: '',
    make: 'BMW',
    model: '330i',
    year: 2023,
    category: 'sedan',
    package: 'gold',
    dailyRate: 89,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-3',
    name: '',
    make: 'Mercedes-Benz',
    model: 'GLC 300',
    year: 2023,
    category: 'suv',
    package: 'gold',
    dailyRate: 99,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-4',
    name: '',
    make: 'Lexus',
    model: 'RX 350',
    year: 2024,
    category: 'suv',
    package: 'gold',
    dailyRate: 105,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1617814076367-b759c0d2e679?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-1',
    name: 'Silver Civic',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    category: 'economy',
    package: 'silver',
    dailyRate: 49,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-2',
    name: '',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    category: 'economy',
    package: 'silver',
    dailyRate: 45,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1590362891995-7a894922c0e5?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-3',
    name: '',
    make: 'Nissan',
    model: 'Altima',
    year: 2022,
    category: 'sedan',
    package: 'silver',
    dailyRate: 55,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-4',
    name: '',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    category: 'suv',
    package: 'silver',
    dailyRate: 65,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1519641471654-76ce5377cb70?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-5',
    name: '',
    make: 'Ford',
    model: 'F-150',
    year: 2020,
    category: 'truck',
    package: 'silver',
    dailyRate: 75,
    seats: 5,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58dd?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-6',
    name: '',
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2021,
    category: 'van',
    package: 'silver',
    dailyRate: 72,
    seats: 7,
    transmission: 'automatic',
    imageUrl:
      'https://images.unsplash.com/photo-1527786356703-4b100181fb4a?auto=format&fit=crop&w=800&q=80',
    unavailableDates: [],
    createdAt: now,
  },
]

export function isDemoVehicleId(id: string) {
  return id.startsWith('demo-')
}
