import { DEMO_VEHICLE_IMAGES } from './assets'
import type { Vehicle } from '../types'

const now = new Date().toISOString()

/** Sample fleet for preview when the database has no vehicles yet. */
export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: 'demo-gold-1',
    name: 'Gold Camry',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2024,
    category: 'sedan',
    package: 'gold',
    dailyRate: 79,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.goldSedan,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-2',
    name: '',
    make: 'BMW',
    model: '330i',
    year: 2023,
    category: 'sedan',
    package: 'gold',
    dailyRate: 89,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.goldBmw,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-3',
    name: '',
    make: 'Mercedes-Benz',
    model: 'GLC 300',
    year: 2023,
    category: 'suv',
    package: 'gold',
    dailyRate: 99,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.goldMercedes,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-gold-4',
    name: '',
    make: 'Lexus',
    model: 'RX 350',
    year: 2024,
    category: 'suv',
    package: 'gold',
    dailyRate: 105,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.goldLexus,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-1',
    name: 'Silver Civic',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    category: 'economy',
    package: 'silver',
    dailyRate: 49,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverCivic,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-2',
    name: '',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    category: 'economy',
    package: 'silver',
    dailyRate: 45,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverCorolla,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-3',
    name: '',
    make: 'Nissan',
    model: 'Altima',
    year: 2022,
    category: 'sedan',
    package: 'silver',
    dailyRate: 55,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverAltima,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-4',
    name: '',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    category: 'suv',
    package: 'silver',
    dailyRate: 65,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverTucson,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-5',
    name: '',
    make: 'Ford',
    model: 'F-150',
    year: 2020,
    category: 'truck',
    package: 'silver',
    dailyRate: 75,
    seats: 5,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverTruck,
    unavailableDates: [],
    createdAt: now,
  },
  {
    id: 'demo-silver-6',
    name: '',
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2021,
    category: 'van',
    package: 'silver',
    dailyRate: 72,
    seats: 7,
    transmission: 'automatic',
    imageUrl: DEMO_VEHICLE_IMAGES.silverVan,
    unavailableDates: [],
    createdAt: now,
  },
]

export function isDemoVehicleId(id: string) {
  return id.startsWith('demo-')
}
